.PHONY: clean All

All:
	@echo "----------Building project:[ FileNº1 - Debug ]----------"
	@cd "FileNº1" && "$(MAKE)" -f  "FileNº1.mk"
clean:
	@echo "----------Cleaning project:[ FileNº1 - Debug ]----------"
	@cd "FileNº1" && "$(MAKE)" -f  "FileNº1.mk" clean
